name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: selenium/standalone-chrome:latest
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install React dependencies
        run: npm install

      - name: Start React App
        run: |
          nohup npm run dev &
        env:
          CI: true

      - name: Setup Python Virtual Environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install robotframework robotframework-seleniumlibrary

      - name: Wait for React App to start
        run: |
          echo "Waiting for React App to start..."
          sleep 30

      - name: Run Robot Tests
        run: |
          source .venv/bin/activate
          robot -d results robot_test/main.robot
