name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: python:3.9-slim  # ใช้ Docker Image ที่มี Python ติดตั้งแล้ว

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Python Dependencies
      - name: Install Python Libraries
        run: |
          python -m pip install --upgrade pip  # อัปเกรด pip
          pip install robotframework  # ติดตั้ง Robot Framework
          pip install robotframework-seleniumlibrary  # ติดตั้ง Selenium Library สำหรับ Robot Framework

      # Start React App in the Background
      - name: Start React App
        run: |
          nohup npm run dev &  # เริ่ม React App เป็น background process
        env:
          CI: true

      # Wait for React App to Start
      - name: Wait for React App to Start
        run: |
          echo "Waiting for React App to start..."
          sleep 30  # รอ 30 วินาทีให้ React App พร้อมใช้งาน

      # Run Robot Framework Tests
      - name: Run Robot Tests
        run: |
          robot ./robot_test  # รัน Robot Framework Tests
