name: Robot Framework

on:
  push:
    branches: [ main ]

  # อนุญาตให้รัน workflow นี้แบบ manual จากแท็บ Actions
  workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up reports directory
          run: |
            chmod -R 777 ${{ github.workspace }}/reports
        - name: Execute tests
          uses: ppodgorsek/robot-framework@latest
          env:
            BROWSER: chrome
            ROBOT_TESTS_DIR: ${{ github.workspace }}/robot_tests
            ROBOT_REPORTS_DIR: ${{ github.workspace }}/reports
            
        - name: Upload test results
          uses: actions/upload-artifact@v3
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports