name: Robot Framework CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  Run-Test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirement.txt') }}
      - name: Install pip dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirement.txt
      - name: Run Test
        run: python -m robot --outputdir results ./test