name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: selenium/standalone-chrome:latest
      options: --user root

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Python Virtual Environment
      - name: Setup Python Virtual Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv python3-pip
          python3 -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies for React App
      - name: Install React dependencies
        run: npm install

      # Start React App in the background
      - name: Start React App
        run: |
          nohup npm run dev &
        env:
          CI: true

      # Wait for React App to Start
      - name: Wait for React App to Start
        run: |
          echo "Waiting for React App to start..."
          sleep 30

      # Run Robot Framework Tests
      - name: Run Robot Tests
        run: |
          . .venv/bin/activate
          robot --loglevel DEBUG -d results robot_test/main.robot
