name: Robot Framework Reporter Demo

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Chromium and Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver

    - name: Run Robot Framework Tests
      uses: joonvena/robotframework-docker-action@v1.0
      with:
        robot_tests_dir: test
      env:
        ROBOT_BROWSER: chrome
        ROBOT_DRIVER_PATH: /usr/bin/chromedriver



    # - name: Store test report
    #   uses: actions/upload-artifact@v2
    #   if: always()
    #   with:
    #     name: reports
    #     path: reports

#   report:
#     if: always()
#     needs: [test]
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Download test report
#       uses: actions/download-artifact@v1
#       with:
#         name: reports
#     - name: Output report
#       uses: joonvena/robotframework-reporter-action@v2
#       with:
#         gh_access_token: ${{ secrets.GITHUB_TOKEN }}