name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: selenium/standalone-chrome:latest  # Docker Image พร้อม Chrome และ ChromeDriver

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9  # ระบุ Python เวอร์ชันที่ต้องการใช้

      # Install Robot Framework and Dependencies
      - name: Install Robot Framework
        run: |
          python -m pip install --upgrade pip
          pip install robotframework robotframework-seleniumlibrary

      # Start React App
      - name: Start React App
        run: |
          nohup npm run dev &  # รัน React App เป็น background process
        env:
          CI: true

      # Wait for React App to Start
      - name: Wait for React App to Start
        run: |
          echo "Waiting for React App to start..."
          sleep 30  # รอ 30 วินาทีให้ React App พร้อม

      # Run Robot Framework Tests
      - name: Run Robot Tests
        run: |
          robot -d results ./robot_test
