name: Robot Framework Reporter Demo

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Setup Node.js (สำหรับโปรเจค React)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # ระบุเวอร์ชัน Node.js ที่ใช้ในโปรเจค

    # Install project dependencies
    - name: Install dependencies
      run: npm install

    # Start React App (Background)
    - name: Start React App
      run: npm start &
      env:
        CI: true

    - name: Run tests
      uses: joonvena/robotframework-docker-action@v1.0
      with:
        robot_tests_dir: test
    # - name: Store test report
    #   uses: actions/upload-artifact@v2
    #   if: always()
    #   with:
    #     name: reports
    #     path: reports

#   report:
#     if: always()
#     needs: [test]
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Download test report
#       uses: actions/download-artifact@v1
#       with:
#         name: reports
#     - name: Output report
#       uses: joonvena/robotframework-reporter-action@v2
#       with:
#         gh_access_token: ${{ secrets.GITHUB_TOKEN }}