name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout source code
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Start React App (Background)
    - name: Start React App
      run: npm run dev &
      env:
        CI: true

    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    # Install Robot Framework
    - name: Install Robot Framework
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary

    # Install Google Chrome and ChromeDriver
    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        # Download the latest ChromeDriver
        CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        wget "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip -d /usr/local/bin/
        rm chromedriver_linux64.zip



    # Run Robot Framework Tests
    - name: Run Robot Tests
      run: |
        robot -d results robot_test/main.robot
